; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Button, x24 y64 w150 h31, Launch with Delay
Gui Add, Button, x192 y64 w150 h31, Launch and Alt-Tab
Gui Add, Edit, x40 y16 w56 h21 +Number, 20
Gui Add, Text, x120 y16 w120 h23 +0x200, Seconds
Gui Add, Button, x360 y64 w150 h31, Launch Normally

Gui Show, w549 h144, Launch Options
Return

GuiEscape:
GuiClose:
    ExitApp
