; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Gui Add, Button, x64 y240 w132 h93, Settings
Gui Add, Text, x112 y16 w320 h155 +0x200, Settings Minimized to Save Resources. Click "Change Settings" to adjust Scale, or Curve. Click Exit or Restart to Close and Restart Artum
Gui Add, Button, x240 y240 w132 h93, Close Artum
Gui Add, Button, x416 y240 w132 h93, Restart Artum

Gui Show, w620 h420, Artum 
Return

GuiEscape:
GuiClose:
    ExitApp
