; Generated by AutoGUI 2.5.8
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1
#Include, artumtest.ahk
/*
Gui Add, Text, x24 y16 w120 h23 +0x200, Artum Screen Cap
Gui Add, CheckBox, vEyes x24 y64 w198 h27, % "     Swap Eyes"
Gui Add, CheckBox, vFlipx x24 y112 w198 h27, % "     Flip Vertical (x)"
Gui Add, CheckBox, vFlipy x23 y155 w198 h27, % "     Flip Horizontal (x)"
Gui Add, Edit, vXCurve x16 y320 w32 h21 +Number, 4
Gui Add, Text, x64 y288 w120 h23 +0x200, Curvature 
Gui Add, Text,  x72 y320 w29 h23 +0x200, X
Gui Add, Text,  x176 y320 w120 h23 +0x200, Y
Gui Add, Edit, vYCurve x112 y320 w32 h21, 0.8
Gui Add, Text, x80 y205 w65 h21 +0x200, Distance
Gui Add, Edit, vDistance  x16 y205 w32 h21 +Number, 20
Gui Add, Text, x88 y245 w120 h23 +0x200, Scale
Gui Add, Edit, vScale  x16 y245 w32 h21 +Number, 10
Gui Add, Button, gSubmit x16 y376 w123 h23, &Save and Launch 

Gui Show, w213 h442, Artum's Screen Cap - Launcher
Return
*/

ReturnJson:=Doer()
for index, value in ReturnJson
{
   msgbox % ReturnJson[index]
}
 x:=ReturnJson[3]
 x:=x * 10
y:=ReturnJson[4]
y:=y * 10
Dist:=ReturnJson[1]
Scale:=ReturnJson[2] 
Gui Font, s20
Gui Add, Text, x30 y20 w386 h58, "Artum Screen Cap"
Gui Add, CheckBox, x30 y90 w310 h43, % "     Swap Eyes"
Gui Add, CheckBox, x30 y150 w395 h79 +Checked, % "     Flip Vertical "
Gui Add, CheckBox, x30 y220 w613 h84, % "     Flip Horizontal "
Gui Add, Edit, vXVar x30 y560 w61 h61, 0
Gui Add, UpDown, gXButs x89 y560 w21 h61 -16
Gui Add, Text, x40 y500 w188 h48, Curvature
Gui Add, Text, x155 y570 w45 h36, X
Gui Add, Text, x410 y561 w38 h36, Y
Gui Add, Edit, vYVar x250 y559 w61 h54, 1
Gui Add, UpDown, gYBut x309 y559 w21 h54 -16
Gui Add, Text, x224 y328 w344 h63, Distance
Gui Add, Edit, vdist x16 y320 w89 h60, %Dist%
Gui Add, UpDown,  x104 y320 w21 h60
Gui Add, Text, x240 y410 w163 h50, Scale
Gui Add, Edit, vScale x20 y400 w88 h63, 1
Gui Add, UpDown, gScaleButs x106 y400 w21 h63 -16
Gui Add, Button, x30 y660 w165 h66, Update
Gui Add, Button, x380 y660 w180 h66, Close App
Gui Add, Button, x206 y660 w168 h66, Relaunch

GuiControl,, Dist, %Dist%
GuiControl,, Scale, %scale%
GuiControl,, Distance, %Distance%
GuiControl,, Distance, %Distance%
Gui Show, w574 h786, Artum's Screen Cap - Launcher (Clone) (Clone)
Return

XButs:
Return

YBut:
Return

DistanceButs:
Return

ScaleButs:
Return

GuiEscape:
GuiClose:
    ExitApp

Gui Show, w459 h629, Artum's Screen Cap - Launcher (Clone)
Return

Submit:
 
GuiControlGet, Scale
GuiControlGet, XCurve
GuiControlGet, YCurve
GuiControlGet, Distance
GuiControlGet, Eyes
GuiControlGet, Flipx
GuiControlGet, Flipy
Msgbox % Flipx Flipy 
VRBat := A_ScriptDir	"\LaunchVRAppwithSettings.bat"
VRApp := A_ScriptDir "\vr-screen-cap.exe"
if (Eyes="1")
    Eyes:="true"
else 
    Eyes:="false"
if (Flipx="1")
    Flipx:="true"
else 
    Flipx:="false"
if (Flipy="1")
    Flipy:="true"
else 
    Flipy:="false"


 filedelete, %VRBat%
            Fileappend, 
            (
@echo off
start "" "%VRApp%" --x-curvature=%XCurve%.0 --Y-curvature=%YCurve% --swap-eyes=%Eyes% --flip-x=%Flipx% --flip-y=%Flipy% --distance=%Distance%.0 --scale=%Scale%.0 
rem 
rem 
rem 
echo: 
echo: 
echo: 
echo: Loading VR Screen Cap and Moving Mountains
echo:  
rem 
rem 
rem 
timeout /t 10
rem 
rem 
rem 
), %VRBat%



/*

RegexMatch(String, "(%(.*?)%)|``(.)", m, spo))

[0-9]+\.\d\d

https://www.autohotkey.com/docs/commands/RegExMatch.htm

https://regex-generator.olafneumann.org/?sampleText=0.00&flags=i&onlyPatterns=false&matchWholeLine=false&selection=0%7CNumber,1%7CCharacter,2%7CDigit,3%7CDigit







var1 := "abc"
var2 := 123
MsgBox % Deref("%var1%def%var2%")  ; Reports abcdef123.

Deref(String)
{
    spo := 1
    out := ""
    while (fpo:=
    {
        out .= SubStr(String, spo, fpo-spo)
        spo := fpo + StrLen(m)
        if (m1)
            out .= %m2%
        else switch (m3)
        {
            case "a": out .= "`a"
            case "b": out .= "`b"
            case "f": out .= "`f"
            case "n": out .= "`n"
            case "r": out .= "`r"
            case "t": out .= "`t"
            case "v": out .= "`v"
            default: out .= m3
        }
    }
    return out SubStr(String, spo)
}


*/